/*******************************************/
/*     FILE GENERATED BY iec2c             */
/* Editing this file is not recommended... */
/*******************************************/

#include "iec_std_lib.h"

#include "accessor.h"

#include "POUS.h"

// CONFIGURATION CONFIG
__DECLARE_GLOBAL(WORD,CONFIG,GVLG0_CAN_AXIS_NUM)
__DECLARE_GLOBAL(WORD,CONFIG,GVLG0_LOCAL_AXIS_NUM)
__DECLARE_GLOBAL(UINT,CONFIG,GVLG0_BOARD_ID)
__DECLARE_GLOBAL(UDINT,CONFIG,GVLG0_KERNEL_VERSION)
__DECLARE_GLOBAL(WORD,CONFIG,GGRP_MBUS_COMMAD)
__DECLARE_GLOBAL(WORD,CONFIG,GGRP_MBUS_ACTPOS)
__DECLARE_GLOBAL(WORD,CONFIG,GGRP_MBUS_ACTVEL)

void RESOURCE1_init__(void);

void config_init__(void) {
  BOOL retain;
  retain = 0;
  __INIT_GLOBAL(WORD,GVLG0_CAN_AXIS_NUM,__INITIAL_VALUE(0),retain)
  __INIT_GLOBAL(WORD,GVLG0_LOCAL_AXIS_NUM,__INITIAL_VALUE(0),retain)
  __INIT_GLOBAL(UINT,GVLG0_BOARD_ID,__INITIAL_VALUE(0),retain)
  __INIT_GLOBAL(UDINT,GVLG0_KERNEL_VERSION,__INITIAL_VALUE(0),retain)
  __INIT_GLOBAL(WORD,GGRP_MBUS_COMMAD,__INITIAL_VALUE(0),retain)
  __INIT_GLOBAL(WORD,GGRP_MBUS_ACTPOS,__INITIAL_VALUE(0),retain)
  __INIT_GLOBAL(WORD,GGRP_MBUS_ACTVEL,__INITIAL_VALUE(0),retain)
  RESOURCE1_init__();
}

void RESOURCE1_run__(unsigned long tick);

void config_run__(unsigned long tick) {
  RESOURCE1_run__(tick);
}
unsigned long long common_ticktime__ = 1000000ULL * 1ULL; /*ns*/
unsigned long greatest_tick_count__ = (unsigned long)0UL; /*tick*/
