
/* Code generated by LPCBus confnode */


#include "iec_std_lib.h"

uint32_t dinData[24];
uint32_t doutData[24];
uint32_t ledData = 0;
uint16_t adc[24];
uint16_t dac[24];

void *input[10];
void *output[10];

static inline int16_t getWord(char *buffer)
{
    return ((int16_t)*buffer<<8) + (int16_t)*(buffer+1);
}

static inline int16_t getWordSwapped(char *buffer)
{
    return (((int16_t)*(buffer+1))<<8) + (int16_t)*buffer;
}

static inline void setWord(char *buffer, int16_t word)
{
    *buffer = (char)(word>>8);
    *(buffer+1) = (char)(word);
}

static inline void setWordSwapped(char *buffer, int16_t word)
{
    *buffer = (char)word;
    *(buffer+1) = (char)(word>>8);
}

static inline int8_t getBit(char *buffer, unsigned char bitOffset)
{
    return (buffer[bitOffset/8] & (0x01 << (bitOffset&0x07))) && 1;
}

static inline void setBit(char *buffer, unsigned char bitOffset, int8_t bit)
{
    unsigned char msk = (0x01 << (bitOffset&0x07));
    if(bit)
        buffer[bitOffset/8] |= msk;
    else
        buffer[bitOffset/8] &= ~msk;
}

static void setWord16(short *buffer, uint16_t word)
{
	*buffer = (short)word;
}

static int16_t getWord16(short *buffer)
{
	return((uint16_t)*buffer);
}

static inline unsigned char getByte(char *buffer)
{
        return((unsigned char)*buffer);
}

static inline void setByte(char *buffer, unsigned char byte)
{
        *buffer = byte;
}

typedef struct
{
	unsigned char status;			/* Current status of timer - running / expired */
	uint64_t actValue;				/* Actual timer value */
	uint64_t toValue;				/* Timeout value - initialized at startup */
	uint64_t oldTime;				/* Time at previous timer increment; NOTE: if RTIME (unsigned long long) changes type, oldTime has to be adapted */
} commTimer;

#define TIM_DISABLED   0
#define TIM_EN_RUNNING   1
#define TIM_EN_EXPIRED   2

#define TIM_DISABLED   0
#define TIM_EN_RUNNING   1
#define TIM_EN_EXPIRED   2





/* LPCBus confnode user variables definition */


/* LPCBus confnode functions */
int __init_0(int argc,char **argv)
{
	for( int i =0; i < 24; ++i) {
		dinData[i] = 0;
		doutData[i] = 0;
		adc[i] = 0;
		dac[i] = 0;
	}
  input[0] = dinData;
input[1] = adc;

output[0] =  doutData;
output[1] =  dac;
output[2] =  &ledData;


  return 0;
}

void __cleanup_0(void)
{
  
}

void __retrieve_0(void)
{
//do something


}
        
void __publish_0(void)
{
//do something





}
