#include "beremiz.h"
#ifndef __POUS_H
#define __POUS_H

#include "accessor.h"
#include "iec_std_lib.h"

__DECLARE_ENUMERATED_TYPE(LOGLEVEL,
  LOGLEVEL__CRITICAL,
  LOGLEVEL__WARNING,
  LOGLEVEL__INFO,
  LOGLEVEL__DEBUG
)
// FUNCTION_BLOCK LOGGER
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(BOOL,TRIG)
  __DECLARE_VAR(STRING,MSG)
  __DECLARE_VAR(LOGLEVEL,LEVEL)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(BOOL,TRIG0)

} LOGGER;

void LOGGER_init__(LOGGER *data__, BOOL retain);
// Code part
void LOGGER_body__(LOGGER *data__);
// FUNCTION
TIME GETCURRENTTIME(
  BOOL EN, 
  BOOL *__ENO, 
  INT MODE);
__DECLARE_STRUCT_TYPE(HYD_AXISMOTION,
  USINT SEGMENTTAG;
    USINT SEGMENTTYPE;
    USINT PLANNER;
    USINT MODE;
    USINT ENDCONDITION;
    USINT DIRECTION;
    REAL SETPOSITION;
    REAL SETVELOCITY;
    REAL SETFLOW;
    REAL SETPRESSURE;
    REAL ACCELERATION;
    REAL DECELERATION;
    REAL DURATION;
    REAL PRESSURERAMPRATE;
    REAL ACTPOSITION;
    REAL ACTVELOCITY;
    REAL ACTFLOW;
    REAL ACTPRESSURE;
    REAL TIMESTAMP;
  )
// FUNCTION_BLOCK HYD_MOVEPROFILE
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(SINT,AXISID)
  __DECLARE_VAR(BOOL,EXECUTE)
  __DECLARE_VAR(HYD_AXISMOTION,MOTION)
  __DECLARE_VAR(INT,BUFFERMODE)
  __DECLARE_VAR(BOOL,DONE)
  __DECLARE_VAR(BOOL,BUSY)
  __DECLARE_VAR(BOOL,ACTIVE)
  __DECLARE_VAR(BOOL,COMMANDABORTED)
  __DECLARE_VAR(BOOL,ERROR)
  __DECLARE_VAR(WORD,ERRORID)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(BOOL,EXECUTE0)
  __DECLARE_VAR(BOOL,DONE0)
  __DECLARE_VAR(BOOL,ACTIVE0)
  __DECLARE_VAR(BOOL,_PENDING)
  __DECLARE_VAR(WORD,_EXEC_ID)

} HYD_MOVEPROFILE;

void HYD_MOVEPROFILE_init__(HYD_MOVEPROFILE *data__, BOOL retain);
// Code part
void HYD_MOVEPROFILE_body__(HYD_MOVEPROFILE *data__);
// FUNCTION_BLOCK HYD_LOADPROFILE
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(SINT,AXISID)
  __DECLARE_VAR(BOOL,EXECUTE)
  __DECLARE_VAR(HYD_AXISMOTION,MOTION)
  __DECLARE_VAR(BOOL,DONE)
  __DECLARE_VAR(BOOL,BUSY)
  __DECLARE_VAR(BOOL,ERROR)
  __DECLARE_VAR(WORD,ERRORID)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(BOOL,EXECUTE0)
  __DECLARE_VAR(BOOL,DONE0)

} HYD_LOADPROFILE;

void HYD_LOADPROFILE_init__(HYD_LOADPROFILE *data__, BOOL retain);
// Code part
void HYD_LOADPROFILE_body__(HYD_LOADPROFILE *data__);
// FUNCTION_BLOCK HYD_STOP
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(SINT,AXISID)
  __DECLARE_VAR(BOOL,EXECUTE)
  __DECLARE_VAR(REAL,DECELERATION)
  __DECLARE_VAR(BOOL,DONE)
  __DECLARE_VAR(BOOL,BUSY)
  __DECLARE_VAR(BOOL,COMMANDABORTED)
  __DECLARE_VAR(BOOL,ERROR)
  __DECLARE_VAR(WORD,ERRORID)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(BOOL,EXECUTE0)
  __DECLARE_VAR(BOOL,DONE0)
  __DECLARE_VAR(BOOL,ACTIVE0)
  __DECLARE_VAR(BOOL,_PENDING)

} HYD_STOP;

void HYD_STOP_init__(HYD_STOP *data__, BOOL retain);
// Code part
void HYD_STOP_body__(HYD_STOP *data__);
// FUNCTION_BLOCK HYD_HOLD
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(SINT,AXISID)
  __DECLARE_VAR(BOOL,EXECUTE)
  __DECLARE_VAR(BOOL,DONE)
  __DECLARE_VAR(BOOL,BUSY)
  __DECLARE_VAR(BOOL,ERROR)
  __DECLARE_VAR(WORD,ERRORID)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(BOOL,EXECUTE0)
  __DECLARE_VAR(BOOL,DONE0)
  __DECLARE_VAR(BOOL,_PENDING)

} HYD_HOLD;

void HYD_HOLD_init__(HYD_HOLD *data__, BOOL retain);
// Code part
void HYD_HOLD_body__(HYD_HOLD *data__);
// FUNCTION_BLOCK HYD_RESUME
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(SINT,AXISID)
  __DECLARE_VAR(BOOL,EXECUTE)
  __DECLARE_VAR(BOOL,DONE)
  __DECLARE_VAR(BOOL,BUSY)
  __DECLARE_VAR(BOOL,ERROR)
  __DECLARE_VAR(WORD,ERRORID)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(BOOL,EXECUTE0)
  __DECLARE_VAR(BOOL,DONE0)
  __DECLARE_VAR(BOOL,_PENDING)

} HYD_RESUME;

void HYD_RESUME_init__(HYD_RESUME *data__, BOOL retain);
// Code part
void HYD_RESUME_body__(HYD_RESUME *data__);
// FUNCTION_BLOCK HYD_MOVEABSOLUTE
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(SINT,AXISID)
  __DECLARE_VAR(BOOL,EXECUTE)
  __DECLARE_VAR(BOOL,CONTINUOUSUPDATE)
  __DECLARE_VAR(REAL,POSITION)
  __DECLARE_VAR(REAL,VELOCITY)
  __DECLARE_VAR(REAL,ACCELERATION)
  __DECLARE_VAR(REAL,DECELERATION)
  __DECLARE_VAR(REAL,JERK)
  __DECLARE_VAR(SINT,DIRECTION)
  __DECLARE_VAR(INT,BUFFERMODE)
  __DECLARE_VAR(BOOL,DONE)
  __DECLARE_VAR(BOOL,BUSY)
  __DECLARE_VAR(BOOL,ACTIVE)
  __DECLARE_VAR(BOOL,COMMANDABORTED)
  __DECLARE_VAR(BOOL,ERROR)
  __DECLARE_VAR(WORD,ERRORID)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(BOOL,EXECUTE0)
  __DECLARE_VAR(BOOL,DONE0)
  __DECLARE_VAR(BOOL,ACTIVE0)
  __DECLARE_VAR(BOOL,_PENDING)
  __DECLARE_VAR(WORD,_EXEC_ID)

} HYD_MOVEABSOLUTE;

void HYD_MOVEABSOLUTE_init__(HYD_MOVEABSOLUTE *data__, BOOL retain);
// Code part
void HYD_MOVEABSOLUTE_body__(HYD_MOVEABSOLUTE *data__);
// FUNCTION_BLOCK HYD_MOVEVELOCITY
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(SINT,AXISID)
  __DECLARE_VAR(BOOL,EXECUTE)
  __DECLARE_VAR(BOOL,CONTINUOUSUPDATE)
  __DECLARE_VAR(REAL,VELOCITY)
  __DECLARE_VAR(REAL,ACCELERATION)
  __DECLARE_VAR(REAL,DECELERATION)
  __DECLARE_VAR(REAL,JERK)
  __DECLARE_VAR(SINT,DIRECTION)
  __DECLARE_VAR(INT,BUFFERMODE)
  __DECLARE_VAR(REAL,PRESSURELIMIT)
  __DECLARE_VAR(BOOL,INVELOCITY)
  __DECLARE_VAR(BOOL,BUSY)
  __DECLARE_VAR(BOOL,ACTIVE)
  __DECLARE_VAR(BOOL,COMMANDABORTED)
  __DECLARE_VAR(BOOL,ERROR)
  __DECLARE_VAR(WORD,ERRORID)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(BOOL,EXECUTE0)
  __DECLARE_VAR(BOOL,INVELOCITY0)
  __DECLARE_VAR(BOOL,ACTIVE0)
  __DECLARE_VAR(BOOL,_PENDING)
  __DECLARE_VAR(WORD,_EXEC_ID)

} HYD_MOVEVELOCITY;

void HYD_MOVEVELOCITY_init__(HYD_MOVEVELOCITY *data__, BOOL retain);
// Code part
void HYD_MOVEVELOCITY_body__(HYD_MOVEVELOCITY *data__);
// FUNCTION_BLOCK HYD_RESET
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(SINT,AXISID)
  __DECLARE_VAR(BOOL,EXECUTE)
  __DECLARE_VAR(BOOL,DONE)
  __DECLARE_VAR(BOOL,BUSY)
  __DECLARE_VAR(BOOL,ERROR)
  __DECLARE_VAR(WORD,ERRORID)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(BOOL,EXECUTE0)
  __DECLARE_VAR(BOOL,DONE0)

} HYD_RESET;

void HYD_RESET_init__(HYD_RESET *data__, BOOL retain);
// Code part
void HYD_RESET_body__(HYD_RESET *data__);
// FUNCTION_BLOCK HYD_PRESSUREHANDLE
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(SINT,AXISID)
  __DECLARE_VAR(BOOL,EXECUTE)
  __DECLARE_VAR(BOOL,CONTINUOUSUPDATE)
  __DECLARE_VAR(REAL,PRESSURE)
  __DECLARE_VAR(REAL,PRESSURERAMPRATE)
  __DECLARE_VAR(REAL,DURATION)
  __DECLARE_VAR(INT,BUFFERMODE)
  __DECLARE_VAR(BOOL,INPRESSURE)
  __DECLARE_VAR(BOOL,DONE)
  __DECLARE_VAR(BOOL,BUSY)
  __DECLARE_VAR(BOOL,ACTIVE)
  __DECLARE_VAR(BOOL,COMMANDABORTED)
  __DECLARE_VAR(BOOL,ERROR)
  __DECLARE_VAR(WORD,ERRORID)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(BOOL,EXECUTE0)
  __DECLARE_VAR(BOOL,INPRESSURE0)
  __DECLARE_VAR(BOOL,ACTIVE0)
  __DECLARE_VAR(BOOL,_PENDING)
  __DECLARE_VAR(WORD,_EXEC_ID)

} HYD_PRESSUREHANDLE;

void HYD_PRESSUREHANDLE_init__(HYD_PRESSUREHANDLE *data__, BOOL retain);
// Code part
void HYD_PRESSUREHANDLE_body__(HYD_PRESSUREHANDLE *data__);
// FUNCTION_BLOCK HYD_CREATEMOTION
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(BOOL,USE_RECIPE)
  __DECLARE_VAR(REAL,FLOW_TO_PUMPSPEED)
  __DECLARE_VAR(REAL,PUMPSPEED_LIMIT)
  __DECLARE_VAR(BOOL,USE_SIMULATION)
  __DECLARE_VAR(SINT,AXISID)
  __DECLARE_VAR(BOOL,DONE)
  __DECLARE_VAR(BOOL,BUSY)
  __DECLARE_VAR(BOOL,ERROR)
  __DECLARE_VAR(WORD,ERRORID)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(BOOL,DONE0)

} HYD_CREATEMOTION;

void HYD_CREATEMOTION_init__(HYD_CREATEMOTION *data__, BOOL retain);
// Code part
void HYD_CREATEMOTION_body__(HYD_CREATEMOTION *data__);
// FUNCTION_BLOCK HYD_SETAXISFEEDBACK
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(SINT,AXISID)
  __DECLARE_VAR(BOOL,ENABLE)
  __DECLARE_VAR(REAL,ACT_POSITION)
  __DECLARE_VAR(REAL,ACT_VELOCITY)
  __DECLARE_VAR(REAL,ACT_FLOW)
  __DECLARE_VAR(REAL,ACT_PRESSURE)
  __DECLARE_VAR(REAL,TIMESTAMP)
  __DECLARE_VAR(BOOL,DONE)
  __DECLARE_VAR(BOOL,BUSY)
  __DECLARE_VAR(BOOL,ERROR)
  __DECLARE_VAR(WORD,ERRORID)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(BOOL,DONE0)

} HYD_SETAXISFEEDBACK;

void HYD_SETAXISFEEDBACK_init__(HYD_SETAXISFEEDBACK *data__, BOOL retain);
// Code part
void HYD_SETAXISFEEDBACK_body__(HYD_SETAXISFEEDBACK *data__);
// FUNCTION_BLOCK HYD_GETPUMPREQUEST
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(BOOL,ENABLE)
  __DECLARE_VAR(SINT,STRATEGY)
  __DECLARE_VAR(REAL,PUMPSPEED)
  __DECLARE_VAR(BOOL,CONFLICT)
  __DECLARE_VAR(BOOL,BUSY)
  __DECLARE_VAR(BOOL,DONE)
  __DECLARE_VAR(BOOL,ERROR)
  __DECLARE_VAR(WORD,ERRORID)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(BOOL,DONE0)

} HYD_GETPUMPREQUEST;

void HYD_GETPUMPREQUEST_init__(HYD_GETPUMPREQUEST *data__, BOOL retain);
// Code part
void HYD_GETPUMPREQUEST_body__(HYD_GETPUMPREQUEST *data__);
// FUNCTION_BLOCK HYD_READSTATUS
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(SINT,AXISID)
  __DECLARE_VAR(BOOL,ENABLE)
  __DECLARE_VAR(BOOL,VALID)
  __DECLARE_VAR(BOOL,BUSY)
  __DECLARE_VAR(BOOL,ERROR)
  __DECLARE_VAR(WORD,ERRORID)
  __DECLARE_VAR(UINT,STATE)
  __DECLARE_VAR(INT,PRESSURECONTROLLERAPPLIED)

  // FB private variables - TEMP, private and located variables

} HYD_READSTATUS;

void HYD_READSTATUS_init__(HYD_READSTATUS *data__, BOOL retain);
// Code part
void HYD_READSTATUS_body__(HYD_READSTATUS *data__);
// FUNCTION_BLOCK HYD_READERROR
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(SINT,AXISID)
  __DECLARE_VAR(BOOL,ENABLE)
  __DECLARE_VAR(BOOL,VALID)
  __DECLARE_VAR(BOOL,BUSY)
  __DECLARE_VAR(BOOL,ERROR)
  __DECLARE_VAR(WORD,ERRORID)

  // FB private variables - TEMP, private and located variables

} HYD_READERROR;

void HYD_READERROR_init__(HYD_READERROR *data__, BOOL retain);
// Code part
void HYD_READERROR_body__(HYD_READERROR *data__);
// FUNCTION_BLOCK HYD_READSIMFEEDBACK
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(SINT,AXISID)
  __DECLARE_VAR(BOOL,ENABLE)
  __DECLARE_VAR(BOOL,VALID)
  __DECLARE_VAR(BOOL,BUSY)
  __DECLARE_VAR(BOOL,ERROR)
  __DECLARE_VAR(WORD,ERRORID)
  __DECLARE_VAR(REAL,POSITION)
  __DECLARE_VAR(REAL,VELOCITY)
  __DECLARE_VAR(REAL,FLOW)
  __DECLARE_VAR(REAL,PRESSURE)

  // FB private variables - TEMP, private and located variables

} HYD_READSIMFEEDBACK;

void HYD_READSIMFEEDBACK_init__(HYD_READSIMFEEDBACK *data__, BOOL retain);
// Code part
void HYD_READSIMFEEDBACK_body__(HYD_READSIMFEEDBACK *data__);
// FUNCTION_BLOCK HYD_READPARAMETER
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(SINT,AXISID)
  __DECLARE_VAR(BOOL,ENABLE)
  __DECLARE_VAR(INT,PARAMETERNUMBER)
  __DECLARE_VAR(BOOL,VALID)
  __DECLARE_VAR(BOOL,BUSY)
  __DECLARE_VAR(BOOL,ERROR)
  __DECLARE_VAR(WORD,ERRORID)
  __DECLARE_VAR(LREAL,VALUE)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(BOOL,ENABLE0)

} HYD_READPARAMETER;

void HYD_READPARAMETER_init__(HYD_READPARAMETER *data__, BOOL retain);
// Code part
void HYD_READPARAMETER_body__(HYD_READPARAMETER *data__);
// FUNCTION_BLOCK HYD_WRITEPARAMETER
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(SINT,AXISID)
  __DECLARE_VAR(BOOL,EXECUTE)
  __DECLARE_VAR(INT,PARAMETERNUMBER)
  __DECLARE_VAR(LREAL,VALUE)
  __DECLARE_VAR(BOOL,DONE)
  __DECLARE_VAR(BOOL,BUSY)
  __DECLARE_VAR(BOOL,ERROR)
  __DECLARE_VAR(WORD,ERRORID)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(BOOL,EXECUTE0)
  __DECLARE_VAR(BOOL,DONE0)

} HYD_WRITEPARAMETER;

void HYD_WRITEPARAMETER_init__(HYD_WRITEPARAMETER *data__, BOOL retain);
// Code part
void HYD_WRITEPARAMETER_body__(HYD_WRITEPARAMETER *data__);
// FUNCTION_BLOCK HYD_READBOOLPARAMETER
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(SINT,AXISID)
  __DECLARE_VAR(BOOL,ENABLE)
  __DECLARE_VAR(INT,PARAMETERNUMBER)
  __DECLARE_VAR(BOOL,VALID)
  __DECLARE_VAR(BOOL,BUSY)
  __DECLARE_VAR(BOOL,ERROR)
  __DECLARE_VAR(WORD,ERRORID)
  __DECLARE_VAR(BOOL,VALUE)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(BOOL,ENABLE0)

} HYD_READBOOLPARAMETER;

void HYD_READBOOLPARAMETER_init__(HYD_READBOOLPARAMETER *data__, BOOL retain);
// Code part
void HYD_READBOOLPARAMETER_body__(HYD_READBOOLPARAMETER *data__);
// FUNCTION_BLOCK HYD_WRITEBOOLPARAMETER
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(SINT,AXISID)
  __DECLARE_VAR(BOOL,EXECUTE)
  __DECLARE_VAR(INT,PARAMETERNUMBER)
  __DECLARE_VAR(BOOL,VALUE)
  __DECLARE_VAR(BOOL,DONE)
  __DECLARE_VAR(BOOL,BUSY)
  __DECLARE_VAR(BOOL,ERROR)
  __DECLARE_VAR(WORD,ERRORID)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(BOOL,EXECUTE0)
  __DECLARE_VAR(BOOL,DONE0)

} HYD_WRITEBOOLPARAMETER;

void HYD_WRITEBOOLPARAMETER_init__(HYD_WRITEBOOLPARAMETER *data__, BOOL retain);
// Code part
void HYD_WRITEBOOLPARAMETER_body__(HYD_WRITEBOOLPARAMETER *data__);
__DECLARE_ENUMERATED_TYPE(HDY_SEGMENTTYPE,
  HDY_SEGMENTTYPE__HDY_SEGMENT_TYPE_CLAMPING,
  HDY_SEGMENTTYPE__HDY_SEGMENT_TYPE_OPENING,
  HDY_SEGMENTTYPE__HDY_SEGMENT_TYPE_INJECTION,
  HDY_SEGMENTTYPE__HDY_SEGMENT_TYPE_HOLDING,
  HDY_SEGMENTTYPE__HDY_SEGMENT_TYPE_EJECTION,
  HDY_SEGMENTTYPE__HDY_SEGMENT_TYPE_CORE_PULL,
  HDY_SEGMENTTYPE__HDY_SEGMENT_TYPE_OTHER
)
__DECLARE_ENUMERATED_TYPE(HDY_PLANNERTYPE,
  HDY_PLANNERTYPE__HDY_PLANNER_POSITION_BASED,
  HDY_PLANNERTYPE__HDY_PLANNER_TIME_BASED
)
__DECLARE_ENUMERATED_TYPE(HDY_CONTROLMODE,
  HDY_CONTROLMODE__HDY_MODE_POSITION,
  HDY_CONTROLMODE__HDY_MODE_SPEED_RAMP,
  HDY_CONTROLMODE__HDY_MODE_PRESSURE_CLOSED_LOOP
)
__DECLARE_ENUMERATED_TYPE(HDY_ENDCONDITIONTYPE,
  HDY_ENDCONDITIONTYPE__HDY_END_POSITION,
  HDY_ENDCONDITIONTYPE__HDY_END_TIME,
  HDY_ENDCONDITIONTYPE__HDY_END_PRESSURE,
  HDY_ENDCONDITIONTYPE__HDY_END_FLOW,
  HDY_ENDCONDITIONTYPE__HDY_END_MANUAL
)
__DECLARE_ENUMERATED_TYPE(HDY_MOTIONDIRECTION,
  HDY_MOTIONDIRECTION__HDY_DIRECTION_AUTO,
  HDY_MOTIONDIRECTION__HDY_DIRECTION_EXTEND,
  HDY_MOTIONDIRECTION__HDY_DIRECTION_RETRACT,
  HDY_MOTIONDIRECTION__HDY_DIRECTION_HOLD
)
__DECLARE_ENUMERATED_TYPE(HDY_PRESSURECONTROLLERTYPE,
  HDY_PRESSURECONTROLLERTYPE__HDY_PRESSURE_CONTROLLER_NONE,
  HDY_PRESSURECONTROLLERTYPE__HDY_PRESSURE_CONTROLLER_P,
  HDY_PRESSURECONTROLLERTYPE__HDY_PRESSURE_CONTROLLER_PI,
  HDY_PRESSURECONTROLLERTYPE__HDY_PRESSURE_CONTROLLER_PID,
  HDY_PRESSURECONTROLLERTYPE__HDY_PRESSURE_CONTROLLER_RBF_PID,
  HDY_PRESSURECONTROLLERTYPE__HDY_PRESSURE_CONTROLLER_RBF_PI
)
__DECLARE_STRUCT_TYPE(HDY_RBFPIDCONFIG,
  REAL MINKP;
    REAL MAXKP;
    REAL MINKI;
    REAL MAXKI;
    REAL MINKD;
    REAL MAXKD;
    REAL ETAW;
    REAL ETAC;
    REAL ETAB;
    REAL ETAP;
    REAL ETAI;
    REAL ETAD;
  )
__DECLARE_STRUCT_TYPE(HDY_MOTIONSEGMENT,
  USINT SEGMENTTAG;
    HDY_SEGMENTTYPE SEGMENTTYPE;
    HDY_PLANNERTYPE PLANNER;
    HDY_CONTROLMODE MODE;
    HDY_ENDCONDITIONTYPE ENDCONDITION;
    HDY_MOTIONDIRECTION DIRECTION;
    REAL TARGETPOSITION;
    REAL TARGETFLOW;
    REAL TARGETPRESSURE;
    REAL MAXACCELERATION;
    REAL MAXVELOCITY;
    REAL MAXFLOW;
    REAL DURATION;
    REAL TOLERANCE;
    REAL POSITIONTOLERANCE;
    REAL PRESSURETOLERANCE;
    REAL FLOWTOLERANCE;
    REAL VELOCITYTOLERANCE;
    REAL TIMEOUTLIMIT;
    REAL VELOCITYTOFLOWGAIN;
    REAL PRESSURERAMPRATE;
    HDY_PRESSURECONTROLLERTYPE PRESSURECONTROLLER;
    REAL PRESSUREKP;
    REAL PRESSUREKI;
    REAL PRESSUREKD;
    REAL PRESSUREINTEGRALLIMIT;
    REAL PRESSUREDEADBAND;
    REAL PRESSUREFILTERALPHA;
    REAL PRESSUREDERIVATIVEFILTERALPHA;
    HDY_RBFPIDCONFIG PRESSURERBFCONFIG;
  )
__DECLARE_STRUCT_TYPE(HDY_AXISREF,
  REAL POSITION;
    REAL VELOCITY;
    REAL FLOW;
    REAL PRESSURE;
    REAL TIMESTAMP;
  )
__DECLARE_ENUMERATED_TYPE(HDY_DIAGNOSTICCODE,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_NONE,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_RECIPE_EMPTY,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_RECIPE_TOO_LARGE,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_SEGMENT_INVALID,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_RUNTIME_CONFIG_INVALID,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_START_CONTEXT_INVALID,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_COMMAND_NOT_ALLOWED,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_NO_RECIPE,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_NO_DIRECT_SEGMENT,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_SEGMENT_INDEX_OUT_OF_RANGE,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_SEGMENT_NOT_COMPLETED,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_RECIPE_ALREADY_FINISHED,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_ABORTED,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_TIMEOUT,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_OVER_PRESSURE,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_UNDER_PRESSURE,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_FLOW_DEVIATION,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_POSITION_DEVIATION,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_VELOCITY_DEVIATION,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_SENSOR_FAULT,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_TIMESTAMP_ROLLBACK,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_PRESSURE_CEILING_EXCEEDED,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_PRESSURE_CEILING_VIOLATED,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_OVER_PRESSURE_LIMIT,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_OVER_PRESSURE_LIMIT_FAULT,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_SOFT_LIMIT_REACHED,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_SOFT_LIMIT_VIOLATED,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_PUMP_DIRECTION_CONFLICT,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_INTERNAL_ERROR,
  HDY_DIAGNOSTICCODE__HDY_DIAG_CODE_BUFFER_FULL
)
__DECLARE_ENUMERATED_TYPE(HDY_CONTROLLERSTATUS,
  HDY_CONTROLLERSTATUS__HDY_STATUS_IDLE,
  HDY_CONTROLLERSTATUS__HDY_STATUS_READY,
  HDY_CONTROLLERSTATUS__HDY_STATUS_RUNNING,
  HDY_CONTROLLERSTATUS__HDY_STATUS_HOLD,
  HDY_CONTROLLERSTATUS__HDY_STATUS_DEGRADED,
  HDY_CONTROLLERSTATUS__HDY_STATUS_SEGMENT_COMPLETE,
  HDY_CONTROLLERSTATUS__HDY_STATUS_FINISHED,
  HDY_CONTROLLERSTATUS__HDY_STATUS_FAULT
)
__DECLARE_ENUMERATED_TYPE(HDY_FBSTATE,
  HDY_FBSTATE__HDY_FB_STATE_DISABLED,
  HDY_FBSTATE__HDY_FB_STATE_IDLE,
  HDY_FBSTATE__HDY_FB_STATE_READY,
  HDY_FBSTATE__HDY_FB_STATE_STARTING,
  HDY_FBSTATE__HDY_FB_STATE_RUNNING,
  HDY_FBSTATE__HDY_FB_STATE_SEGMENT_COMPLETE,
  HDY_FBSTATE__HDY_FB_STATE_HOLD,
  HDY_FBSTATE__HDY_FB_STATE_DONE,
  HDY_FBSTATE__HDY_FB_STATE_ABORTED,
  HDY_FBSTATE__HDY_FB_STATE_FAULT
)
__DECLARE_STRUCT_TYPE(HDY_EXECUTIONREFERENCE,
  REAL ELAPSEDTIME;
    REAL PRESSUREREFERENCE;
    REAL FLOWREFERENCE;
    REAL VELOCITYREFERENCE;
  )
__DECLARE_STRUCT_TYPE(HDY_PRESSURELOOPSTATE,
  REAL TARGETPRESSURE;
    REAL FILTEREDPRESSURE;
    REAL FILTEREDPRESSURERATE;
    REAL CONTROLERROR;
    REAL FEEDFORWARDFLOW;
    REAL FEEDBACKFLOW;
    REAL OUTPUTFLOW;
    REAL UNSATURATEDOUTPUTFLOW;
    REAL SAMPLINGPERIOD;
    REAL ADAPTIVEKP;
    REAL ADAPTIVEKI;
    REAL ADAPTIVEKD;
    REAL ADAPTIVEJACOBIAN;
    REAL TRACKINGAPPLIED;
    REAL SATURATED;
    REAL ADAPTIVEACTIVE;
  )
__DECLARE_ENUMERATED_TYPE(HDY_PROTECTIONACTION,
  HDY_PROTECTIONACTION__HDY_PROTECTION_ACTION_NONE,
  HDY_PROTECTIONACTION__HDY_PROTECTION_ACTION_WARNING,
  HDY_PROTECTIONACTION__HDY_PROTECTION_ACTION_DERATE,
  HDY_PROTECTIONACTION__HDY_PROTECTION_ACTION_STOP
)
__DECLARE_ENUMERATED_TYPE(HDY_SEGMENTSOURCE,
  HDY_SEGMENTSOURCE__HDY_SEGMENT_SOURCE_NONE,
  HDY_SEGMENTSOURCE__HDY_SEGMENT_SOURCE_RECIPE,
  HDY_SEGMENTSOURCE__HDY_SEGMENT_SOURCE_DIRECT
)
__DECLARE_ENUMERATED_TYPE(HDY_DIAGNOSTICSEVERITY,
  HDY_DIAGNOSTICSEVERITY__HDY_DIAG_SEVERITY_NONE,
  HDY_DIAGNOSTICSEVERITY__HDY_DIAG_SEVERITY_INFO,
  HDY_DIAGNOSTICSEVERITY__HDY_DIAG_SEVERITY_WARNING,
  HDY_DIAGNOSTICSEVERITY__HDY_DIAG_SEVERITY_FAULT
)
__DECLARE_ENUMERATED_TYPE(HDY_DIAGNOSTICSOURCE,
  HDY_DIAGNOSTICSOURCE__HDY_DIAG_SOURCE_NONE,
  HDY_DIAGNOSTICSOURCE__HDY_DIAG_SOURCE_RECIPE,
  HDY_DIAGNOSTICSOURCE__HDY_DIAG_SOURCE_RUNTIME,
  HDY_DIAGNOSTICSOURCE__HDY_DIAG_SOURCE_COMMAND,
  HDY_DIAGNOSTICSOURCE__HDY_DIAG_SOURCE_EXECUTION,
  HDY_DIAGNOSTICSOURCE__HDY_DIAG_SOURCE_SENSOR,
  HDY_DIAGNOSTICSOURCE__HDY_DIAG_SOURCE_INTERNAL
)
__DECLARE_ENUMERATED_TYPE(HDY_DIAGNOSTICRECOVERY,
  HDY_DIAGNOSTICRECOVERY__HDY_DIAG_RECOVERY_NONE,
  HDY_DIAGNOSTICRECOVERY__HDY_DIAG_RECOVERY_AUTO_CLEAR,
  HDY_DIAGNOSTICRECOVERY__HDY_DIAG_RECOVERY_CHECK_COMMAND,
  HDY_DIAGNOSTICRECOVERY__HDY_DIAG_RECOVERY_CHECK_SENSOR,
  HDY_DIAGNOSTICRECOVERY__HDY_DIAG_RECOVERY_RELOAD_RECIPE,
  HDY_DIAGNOSTICRECOVERY__HDY_DIAG_RECOVERY_RESTART_SEGMENT,
  HDY_DIAGNOSTICRECOVERY__HDY_DIAG_RECOVERY_RESET_CONTROLLER
)
__DECLARE_STRUCT_TYPE(HDY_DIAGNOSTICINFO,
  HDY_DIAGNOSTICCODE CODE;
    HDY_DIAGNOSTICSEVERITY SEVERITY;
    HDY_DIAGNOSTICSOURCE SOURCE;
    HDY_DIAGNOSTICRECOVERY RECOVERY;
    HDY_PROTECTIONACTION PROTECTIONACTION;
    UINT FLAGS;
    BOOL OVERPRESSURE;
    BOOL UNDERPRESSURE;
    BOOL FLOWDEVIATION;
    BOOL POSITIONDEVIATION;
    BOOL VELOCITYDEVIATION;
    BOOL TIMEOUT;
    BOOL SENSORFAULT;
    BOOL TIMESTAMPROLLBACK;
    BOOL PRESSUREERROR;
    BOOL FLOWERROR;
    BOOL VELOCITYERROR;
  )
__DECLARE_STRUCT_TYPE(HDY_DIAGNOSTICSNAPSHOT,
  BOOL VALID;
    REAL EVENTTIMESTAMP;
    USINT SEGMENTINDEX;
    HDY_CONTROLLERSTATUS STATUS;
    BOOL ACTIVE;
    BOOL FINISHED;
    BOOL FAULT;
    HDY_DIAGNOSTICINFO DIAGNOSTIC;
    HDY_AXISREF AXISREF;
    HDY_EXECUTIONREFERENCE REFERENCES;
    USINT SEGMENTTAG;
  )
__DECLARE_STRUCT_TYPE(HDY_DIAGNOSTICHISTORY,
  HDY_DIAGNOSTICINFO LASTSNAPSHOT;
    UINT TOTALRECORDED;
    BOOL HASRECORD;
  )
__DECLARE_STRUCT_TYPE(HDY_MOTIONSTATE,
  UINT CURRENTSEGMENTINDEX;
    BOOL ACTIVE;
    BOOL FINISHED;
    BOOL FAULTACTIVE;
    REAL PLANNEDVELOCITY;
    REAL PLANNEDFLOW;
    REAL COMMANDEDPUMPSPEED;
    HDY_EXECUTIONREFERENCE REFERENCES;
    HDY_PRESSURECONTROLLERTYPE PRESSURECONTROLLERAPPLIED;
    HDY_PRESSURELOOPSTATE PRESSURELOOP;
    HDY_PROTECTIONACTION PROTECTIONACTION;
    HDY_MOTIONDIRECTION PLANNEDDIRECTION;
    HDY_SEGMENTSOURCE SEGMENTSOURCE;
    HDY_CONTROLLERSTATUS STATUS;
    USINT CURRENTSEGMENTTAG;
  )
__DECLARE_STRUCT_TYPE(HDY_ERRORMONITOR,
  REAL POSITIONERROR;
    REAL VELOCITYERROR;
    REAL FLOWERROR;
    REAL PRESSUREERROR;
    BOOL POSITIONERRORACTIVE;
    BOOL VELOCITYERRORACTIVE;
    BOOL FLOWERRORACTIVE;
    BOOL PRESSUREERRORACTIVE;
    REAL POSITIONERRORSTARTTIME;
    REAL VELOCITYERRORSTARTTIME;
    REAL FLOWERRORSTARTTIME;
    REAL PRESSUREERRORSTARTTIME;
    REAL POSITIONERRORDURATION;
    REAL VELOCITYERRORDURATION;
    REAL FLOWERRORDURATION;
    REAL PRESSUREERRORDURATION;
    REAL MAXPOSITIONERROR;
    REAL MINPOSITIONERROR;
    REAL AVGPOSITIONERROR;
    REAL MAXVELOCITYERROR;
    REAL MINVELOCITYERROR;
    REAL AVGVELOCITYERROR;
    REAL MAXFLOWERROR;
    REAL MINFLOWERROR;
    REAL AVGFLOWERROR;
    REAL MAXPRESSUREERROR;
    REAL MINPRESSUREERROR;
    REAL AVGPRESSUREERROR;
    UINT SAMPLECOUNT;
  )
__DECLARE_ENUMERATED_TYPE(HDY_FBCOMMAND,
  HDY_FBCOMMAND__HDY_CMD_NONE,
  HDY_FBCOMMAND__HDY_CMD_START,
  HDY_FBCOMMAND__HDY_CMD_NEXT,
  HDY_FBCOMMAND__HDY_CMD_STOP,
  HDY_FBCOMMAND__HDY_CMD_HOLD,
  HDY_FBCOMMAND__HDY_CMD_RESUME,
  HDY_FBCOMMAND__HDY_CMD_ABORT,
  HDY_FBCOMMAND__HDY_CMD_RESET,
  HDY_FBCOMMAND__HDY_CMD_ACK
)
__DECLARE_STRUCT_TYPE(HDY_RAMPCONTROLLER,
  REAL RAMPEDPRESSURE;
    REAL LASTTIMESTAMP;
  )
__DECLARE_STRUCT_TYPE(HDY_AXISMOTION222,
  USINT SEGMENTTAG;
    USINT PLANNER;
    USINT MODE;
    USINT ENDCONDITION;
    USINT DIRECTION;
    REAL SETPOSITION;
    REAL SETVELOCITY;
    REAL SETFLOW;
    REAL SETPRESSURE;
    REAL ACCELERATION;
    REAL DECELERATION;
    REAL DURATION;
    REAL PRESSURERAMPRATE;
    REAL ACTPOSITION;
    REAL ACTVELOCITY;
    REAL ACTFLOW;
    REAL ACTPRESSURE;
    REAL TIMESTAMP;
  )
__DECLARE_ARRAY_TYPE(__ARRAY_OF_REAL_500,REAL,[500])
// FUNCTION_BLOCK FIRSTORDERSYSTEM
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(BOOL,ENABLE)
  __DECLARE_VAR(REAL,MOTORVELOCITY)
  __DECLARE_VAR(REAL,TCYCLE)
  __DECLARE_VAR(REAL,KNUM)
  __DECLARE_VAR(REAL,TTAU)
  __DECLARE_VAR(REAL,DELAYTIME)
  __DECLARE_VAR(REAL,PRESSURE)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(UINT,MAXDELAYSTEPS)
  __DECLARE_VAR(REAL,PRE_PRESSURE)
  __DECLARE_VAR(REAL,DISTURBANCE)
  __DECLARE_VAR(REAL,TCURR)
  __DECLARE_VAR(DINT,DELAYSTEPS)
  __DECLARE_VAR(__ARRAY_OF_REAL_500,OUTPUTBUFFER)
  __DECLARE_VAR(UINT,BUFFERINDEX)
  __DECLARE_VAR(REAL,CURRENTOUTPUT)
  __DECLARE_VAR(DINT,DELAYINDEX)
  __DECLARE_VAR(DINT,I)
  __DECLARE_VAR(REAL,DISTURBANCESIGNAL)

} FIRSTORDERSYSTEM;

void FIRSTORDERSYSTEM_init__(FIRSTORDERSYSTEM *data__, BOOL retain);
// Code part
void FIRSTORDERSYSTEM_body__(FIRSTORDERSYSTEM *data__);
// FUNCTION_BLOCK FB_HYDAXIS3
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(BOOL,BSTART)
  __DECLARE_VAR(BOOL,BSTOP)
  __DECLARE_VAR(BOOL,BESTOP)
  __DECLARE_VAR(BOOL,BRESET)
  __DECLARE_VAR(UINT,UIDIR)
  __DECLARE_VAR(UINT,UIMODE)
  __DECLARE_VAR(UINT,UIPRES)
  __DECLARE_VAR(UINT,UISPD)
  __DECLARE_VAR(UDINT,UDIPOS)
  __DECLARE_VAR(UINT,UIFORCE)
  __DECLARE_VAR(UINT,UIACC)
  __DECLARE_VAR(UINT,UIDEC)
  __DECLARE_VAR(UINT,UIJERK)
  __DECLARE_VAR(BOOL,BBUSY)
  __DECLARE_VAR(BOOL,BDONE)
  __DECLARE_VAR(BOOL,BINVELOCITY)
  __DECLARE_VAR(BOOL,BINPRESSURE)
  __DECLARE_VAR(BOOL,BALARM)
  __DECLARE_VAR(DWORD,DWALARMID)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(INT,ISTEP)
  HYD_CREATEMOTION FBCREATE;
  HYD_MOVEABSOLUTE FBMOVEABS;
  HYD_MOVEVELOCITY FBMOVEVEL;
  HYD_PRESSUREHANDLE FBPRESHDL;
  HYD_STOP FBSTOP;
  HYD_STOP FBESTOP;
  HYD_RESET FBRESET;
  HYD_READSIMFEEDBACK FBREADFB;
  __DECLARE_VAR(SINT,SIAXISID)
  R_TRIG RTRIGSTART;
  R_TRIG RTRIGSTOP;
  R_TRIG RTRIGESTOP;
  R_TRIG RTRIGRESET;
  __DECLARE_VAR(UINT,UIACTIVEMODE)
  __DECLARE_VAR(BOOL,BCMDEXECUTE)
  __DECLARE_VAR(REAL,RPOS)
  __DECLARE_VAR(REAL,RVEL)
  __DECLARE_VAR(REAL,RPRES)
  __DECLARE_VAR(REAL,RACC)
  __DECLARE_VAR(REAL,RDEC)
  __DECLARE_VAR(REAL,RJERK)
  __DECLARE_VAR(BOOL,BFBERROR)
  __DECLARE_VAR(WORD,WFBERRORID)
  __DECLARE_VAR(SINT,IDIR)
  __DECLARE_VAR(REAL,RPOSITION)
  __DECLARE_VAR(REAL,RVELOCTITY)
  __DECLARE_VAR(REAL,RFLOW)
  __DECLARE_VAR(REAL,RPERSSURE)

} FB_HYDAXIS3;

void FB_HYDAXIS3_init__(FB_HYDAXIS3 *data__, BOOL retain);
// Code part
void FB_HYDAXIS3_body__(FB_HYDAXIS3 *data__);
// FUNCTION_BLOCK FB_HYDAXIS1
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(BOOL,BSTART)
  __DECLARE_VAR(BOOL,BSTOP)
  __DECLARE_VAR(BOOL,BESTOP)
  __DECLARE_VAR(BOOL,BRESET)
  __DECLARE_VAR(UINT,UIDIR)
  __DECLARE_VAR(UINT,UIMODE)
  __DECLARE_VAR(UINT,UIPRES)
  __DECLARE_VAR(UINT,UISPD)
  __DECLARE_VAR(UDINT,UDIPOS)
  __DECLARE_VAR(UINT,UIFORCE)
  __DECLARE_VAR(UINT,UIACC)
  __DECLARE_VAR(UINT,UIDEC)
  __DECLARE_VAR(UINT,UIJERK)
  __DECLARE_VAR(BOOL,BBUSY)
  __DECLARE_VAR(BOOL,BDONE)
  __DECLARE_VAR(BOOL,BALARM)
  __DECLARE_VAR(DWORD,DWALARMID)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(INT,ISTEP)
  HYD_CREATEMOTION FBHYD_CREATEMOTION;
  HYD_MOVEABSOLUTE FBHYD_MOVEABSOLUTE;
  HYD_MOVEVELOCITY FBHYD_MOVEVELOCITY;
  HYD_PRESSUREHANDLE FBHYD_PRESSUREHANDLE;
  HYD_READSIMFEEDBACK FBHYD_READSIMFEEDBACK;
  HYD_STOP FBHYD_STOP;
  HYD_STOP FBHYD_ESTOP;
  HYD_RESET FBHYD_RESET;
  __DECLARE_VAR(SINT,SIAXISID)
  __DECLARE_VAR(REAL,RPOSITION)
  __DECLARE_VAR(REAL,RVELOCTITY)
  __DECLARE_VAR(REAL,RFLOW)
  __DECLARE_VAR(REAL,RPERSSURE)
  __DECLARE_VAR(SINT,IDIR)
  R_TRIG RTRIGSTART;
  R_TRIG RTRIGSTOP;
  R_TRIG RTRIGESTOP;
  R_TRIG RTRIGRESET;
  __DECLARE_VAR(REAL,RTARGETPOS)
  __DECLARE_VAR(REAL,RTARGETVEL)
  __DECLARE_VAR(REAL,RTARGETPRES)
  __DECLARE_VAR(REAL,RTARGETACC)
  __DECLARE_VAR(REAL,RTARGETDEC)
  __DECLARE_VAR(REAL,RTARGETJERK)

} FB_HYDAXIS1;

void FB_HYDAXIS1_init__(FB_HYDAXIS1 *data__, BOOL retain);
// Code part
void FB_HYDAXIS1_body__(FB_HYDAXIS1 *data__);
// FUNCTION_BLOCK FB_HYDAXIS2
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(BOOL,BSTART)
  __DECLARE_VAR(BOOL,BSTOP)
  __DECLARE_VAR(BOOL,BESTOP)
  __DECLARE_VAR(BOOL,BRESET)
  __DECLARE_VAR(UINT,UIDIR)
  __DECLARE_VAR(UINT,UIMODE)
  __DECLARE_VAR(UINT,UIPRES)
  __DECLARE_VAR(UINT,UISPD)
  __DECLARE_VAR(UDINT,UDIPOS)
  __DECLARE_VAR(UINT,UIFORCE)
  __DECLARE_VAR(UINT,UIACC)
  __DECLARE_VAR(UINT,UIDEC)
  __DECLARE_VAR(UINT,UIJERK)
  __DECLARE_VAR(BOOL,BBUSY)
  __DECLARE_VAR(BOOL,BDONE)
  __DECLARE_VAR(BOOL,BALARM)
  __DECLARE_VAR(DWORD,DWALARMID)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(INT,ISTEP)
  __DECLARE_VAR(SINT,IDIR)
  HYD_CREATEMOTION FBCREATE;
  HYD_MOVEABSOLUTE FBMOVEABS;
  HYD_MOVEVELOCITY FBMOVEVEL;
  HYD_PRESSUREHANDLE FBPRESHDL;
  HYD_STOP FBSTOP;
  HYD_STOP FBESTOP;
  HYD_RESET FBRESET;
  HYD_READSIMFEEDBACK FBREADFB;
  __DECLARE_VAR(SINT,SIAXISID)
  __DECLARE_VAR(REAL,RPOSITION)
  __DECLARE_VAR(REAL,RVELOCTITY)
  __DECLARE_VAR(REAL,RFLOW)
  __DECLARE_VAR(REAL,RPERSSURE)
  R_TRIG RTRIGSTART;
  R_TRIG RTRIGSTOP;
  R_TRIG RTRIGESTOP;
  R_TRIG RTRIGRESET;
  __DECLARE_VAR(UINT,UIACTIVEMODE)
  __DECLARE_VAR(BOOL,BCMDEXECUTE)
  __DECLARE_VAR(REAL,RPOS)
  __DECLARE_VAR(REAL,RVEL)
  __DECLARE_VAR(REAL,RPRES)
  __DECLARE_VAR(REAL,RACC)
  __DECLARE_VAR(REAL,RDEC)
  __DECLARE_VAR(REAL,RJERK)
  __DECLARE_VAR(BOOL,BFBDONE)
  __DECLARE_VAR(BOOL,BFBERROR)
  __DECLARE_VAR(WORD,WFBERRORID)

} FB_HYDAXIS2;

void FB_HYDAXIS2_init__(FB_HYDAXIS2 *data__, BOOL retain);
// Code part
void FB_HYDAXIS2_body__(FB_HYDAXIS2 *data__);
// FUNCTION_BLOCK FB_WORDBITRISING
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(WORD,WORDIN)
  __DECLARE_VAR(INT,BITPOS)
  __DECLARE_VAR(BOOL,RISING)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(BOOL,PREVBIT)
  __DECLARE_VAR(BOOL,CURRENTBIT)
  __DECLARE_VAR(WORD,WTMP)

} FB_WORDBITRISING;

void FB_WORDBITRISING_init__(FB_WORDBITRISING *data__, BOOL retain);
// Code part
void FB_WORDBITRISING_body__(FB_WORDBITRISING *data__);
// PROGRAM TESTVECLOCITY
// Data part
typedef struct {
  // PROGRAM Interface - IN, OUT, IN_OUT variables

  // PROGRAM private variables - TEMP, private and located variables
  __DECLARE_VAR(DINT,NEWLOCALVAR0)
  __DECLARE_VAR(REAL,NEWLOCALVAR1)
  __DECLARE_VAR(REAL,FPOS)
  __DECLARE_VAR(REAL,FVEL)
  __DECLARE_VAR(REAL,FFLOW)
  __DECLARE_VAR(REAL,FPRESSURE)
  __DECLARE_VAR(DINT,ISTEP)
  __DECLARE_VAR(BOOL,BERROR)
  __DECLARE_VAR(WORD,WERRORID)
  __DECLARE_VAR(SINT,IAXIS0)
  __DECLARE_VAR(BOOL,BTEMP)
  TON TDELAY;
  HYD_CREATEMOTION FBHDY_CREATEMOTION;
  HYD_MOVEVELOCITY FBHYD_MOVEVELOCITY;
  HYD_READSIMFEEDBACK FBHYD_READSIMFEEDBACK;
  HYD_READSTATUS FBHYD_READSTATUS;
  HYD_SETAXISFEEDBACK FBHYD_SETAXISFEEDBACK;
  __DECLARE_VAR(UINT,ISTATE)
  __DECLARE_VAR(BOOL,BACTIVE)
  __DECLARE_VAR(BOOL,BEXECUTE)
  __DECLARE_VAR(REAL,TCYCLE)
  FB_WORDBITRISING CMD0_DETECT;
  HYD_STOP FBHYD_STOP;
  __DECLARE_VAR(REAL,FSETVEL)
  __DECLARE_EXTERNAL(WORD,GGRP_MBUS_ACTPOS)
  __DECLARE_EXTERNAL(WORD,GGRP_MBUS_COMMAD)
  __DECLARE_EXTERNAL(WORD,GGRP_MBUS_ACTVEL)

} TESTVECLOCITY;

void TESTVECLOCITY_init__(TESTVECLOCITY *data__, BOOL retain);
// Code part
void TESTVECLOCITY_body__(TESTVECLOCITY *data__);
// PROGRAM TESTMOTION
// Data part
typedef struct {
  // PROGRAM Interface - IN, OUT, IN_OUT variables

  // PROGRAM private variables - TEMP, private and located variables
  __DECLARE_VAR(DINT,NEWLOCALVAR0)
  __DECLARE_VAR(UDINT,NEWLOCALVAR2)
  __DECLARE_VAR(REAL,NEWLOCALVAR1)
  __DECLARE_VAR(REAL,FPOS)
  __DECLARE_VAR(REAL,FVEL)
  __DECLARE_VAR(REAL,FFLOW)
  __DECLARE_VAR(REAL,FPRESSURE)
  __DECLARE_VAR(DINT,ISTEP)
  __DECLARE_VAR(BOOL,BERROR)
  __DECLARE_VAR(BOOL,BVALID)
  __DECLARE_VAR(WORD,WERRORID)
  __DECLARE_VAR(SINT,IAXIS0)
  __DECLARE_VAR(BOOL,BTEMP)
  TON TDELAY;
  HYD_CREATEMOTION FBHDY_CREATEMOTION;
  HYD_MOVEABSOLUTE FBHYD_MOVEABSOLUTE;
  HYD_READSIMFEEDBACK FBHYD_READSIMFEEDBACK;
  HYD_READSTATUS FBHYD_READSTATUS;
  HYD_SETAXISFEEDBACK FBHYD_SETAXISFEEDBACK;
  __DECLARE_VAR(UINT,ISTATE)
  __DECLARE_VAR(BOOL,BACTIVE)
  __DECLARE_VAR(REAL,TCYCLE)
  FB_WORDBITRISING CMD0_DETECT;
  HYD_STOP FBHYD_STOP;
  HYD_PRESSUREHANDLE FBHYD_PRESSUREHANDLE;
  __DECLARE_EXTERNAL(WORD,GGRP_MBUS_ACTPOS)
  __DECLARE_EXTERNAL(WORD,GGRP_MBUS_COMMAD)
  __DECLARE_EXTERNAL(WORD,GGRP_MBUS_ACTVEL)

} TESTMOTION;

void TESTMOTION_init__(TESTMOTION *data__, BOOL retain);
// Code part
void TESTMOTION_body__(TESTMOTION *data__);
// FUNCTION_BLOCK AXISMOTIONDEMO
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(HDY_AXISREF,IHDYAXIS)

  // FB private variables - TEMP, private and located variables
  __DECLARE_VAR(DINT,NEWLOCALVAR0)

} AXISMOTIONDEMO;

void AXISMOTIONDEMO_init__(AXISMOTIONDEMO *data__, BOOL retain);
// Code part
void AXISMOTIONDEMO_body__(AXISMOTIONDEMO *data__);
// FUNCTION_BLOCK AXISMOTIONCONTROL222
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(BOOL,EXECUTE)
  __DECLARE_VAR(HDY_AXISMOTION222,MOTION)
  __DECLARE_VAR(BOOL,ACTIVE)
  __DECLARE_VAR(BOOL,BUSY)
  __DECLARE_VAR(BOOL,DONE)
  __DECLARE_VAR(BOOL,ERROR)
  __DECLARE_VAR(WORD,ERRORID)
  __DECLARE_VAR(WORD,STATE)
  __DECLARE_VAR(REAL,PUMP_SPEED)

  // FB private variables - TEMP, private and located variables

} AXISMOTIONCONTROL222;

void AXISMOTIONCONTROL222_init__(AXISMOTIONCONTROL222 *data__, BOOL retain);
// Code part
void AXISMOTIONCONTROL222_body__(AXISMOTIONCONTROL222 *data__);
// FUNCTION_BLOCK HDY_INJECTSIMULATOR222
// Data part
typedef struct {
  // FB Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,EN)
  __DECLARE_VAR(BOOL,ENO)
  __DECLARE_VAR(BOOL,ENABLE)
  __DECLARE_VAR(REAL,CYCLE_TIME)
  __DECLARE_VAR(REAL,CMD_RPM)
  __DECLARE_VAR(USINT,PUMP_OWNER_AXIS)
  __DECLARE_VAR(SINT,DIRECTION)
  __DECLARE_VAR(REAL,PRESSURE_BIAS)
  __DECLARE_VAR(REAL,PRESSURE_SCALE)
  __DECLARE_VAR(BOOL,ACTIVE)
  __DECLARE_VAR(REAL,POS_MM)
  __DECLARE_VAR(REAL,VEL_MM_S)
  __DECLARE_VAR(REAL,PRESSURE_BAR)

  // FB private variables - TEMP, private and located variables

} HDY_INJECTSIMULATOR222;

void HDY_INJECTSIMULATOR222_init__(HDY_INJECTSIMULATOR222 *data__, BOOL retain);
// Code part
void HDY_INJECTSIMULATOR222_body__(HDY_INJECTSIMULATOR222 *data__);
// PROGRAM TESTFBHYDAXIS
// Data part
typedef struct {
  // PROGRAM Interface - IN, OUT, IN_OUT variables

  // PROGRAM private variables - TEMP, private and located variables
  __DECLARE_VAR(DINT,NEWLOCALVAR0)
  FB_HYDAXIS3 FBAXIS;
  __DECLARE_VAR(BOOL,START)
  __DECLARE_VAR(BOOL,STOP)
  __DECLARE_VAR(UINT,IMODE)
  __DECLARE_VAR(UINT,IDIR)
  __DECLARE_VAR(BOOL,BUSY)
  __DECLARE_VAR(BOOL,ERR)
  __DECLARE_VAR(DWORD,ERRID)
  __DECLARE_VAR(UDINT,FSETPOS)

} TESTFBHYDAXIS;

void TESTFBHYDAXIS_init__(TESTFBHYDAXIS *data__, BOOL retain);
// Code part
void TESTFBHYDAXIS_body__(TESTFBHYDAXIS *data__);
// PROGRAM TESTSTANDFB
// Data part
typedef struct {
  // PROGRAM Interface - IN, OUT, IN_OUT variables

  // PROGRAM private variables - TEMP, private and located variables
  __DECLARE_VAR(INT,ISTEP)
  __DECLARE_VAR(BOOL,BINVEL)
  __DECLARE_VAR(UDINT,ICNT)
  __DECLARE_VAR(LREAL,FSETVEL)
  __DECLARE_VAR(LREAL,FACTVEL)
  __DECLARE_VAR(LREAL,FACTPOS)
  __DECLARE_VAR(BOOL,BBUSY)
  __DECLARE_VAR(BOOL,BERR)
  __DECLARE_VAR(BOOL,BABORT)
  __DECLARE_VAR(BOOL,BACTIVE)
  __DECLARE_VAR(WORD,WERR)

} TESTSTANDFB;

void TESTSTANDFB_init__(TESTSTANDFB *data__, BOOL retain);
// Code part
void TESTSTANDFB_body__(TESTSTANDFB *data__);
// PROGRAM TESTPRESSURECTRL
// Data part
typedef struct {
  // PROGRAM Interface - IN, OUT, IN_OUT variables

  // PROGRAM private variables - TEMP, private and located variables
  __DECLARE_VAR(DINT,NEWLOCALVAR0)
  FIRSTORDERSYSTEM HYDRAULIC_SYS;
  HYD_GETPUMPREQUEST FBHYD_GETPUMPREQUEST;
  HYD_CREATEMOTION FBHDY_CREATEMOTION;
  HYD_PRESSUREHANDLE FBHYD_PRESSUREHANDLE;
  HYD_READSIMFEEDBACK FBHYD_READSIMFEEDBACK;
  HYD_READSTATUS FBHYD_READSTATUS;
  HYD_SETAXISFEEDBACK FBHYD_SETAXISFEEDBACK;
  __DECLARE_VAR(REAL,FPIDOUTPUT)
  __DECLARE_VAR(REAL,FTARGETPRESSURE)
  __DECLARE_VAR(INT,ISTEP)
  __DECLARE_VAR(SINT,IAXIS0)
  __DECLARE_VAR(BOOL,BINPRESSURE)
  __DECLARE_VAR(BOOL,BDONE)
  __DECLARE_VAR(BOOL,BACT)
  __DECLARE_VAR(BOOL,BABORTED)
  __DECLARE_VAR(BOOL,BERR)
  __DECLARE_VAR(BOOL,BBUSY)
  __DECLARE_VAR(WORD,WERRID)
  __DECLARE_VAR(REAL,TCYCLE)
  __DECLARE_VAR(REAL,TIMECYCLE)
  __DECLARE_VAR(REAL,FACTPRESSURE)
  __DECLARE_VAR(REAL,FSETPRESSURE)
  HYD_WRITEPARAMETER FBHYD_WRITEPARAMETER;

} TESTPRESSURECTRL;

void TESTPRESSURECTRL_init__(TESTPRESSURECTRL *data__, BOOL retain);
// Code part
void TESTPRESSURECTRL_body__(TESTPRESSURECTRL *data__);
#endif //__POUS_H
